week9/day-3/iron_topics/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root "topics#index"

  mount Sidekiq::Web => '/secret_sidekiq'

  resources :topics, except: [:destroy] do
    collection do
      get :search
    end

    resources :interests, only: [:index, :show, :create] do
      collection do
        post :filter
      end
    end
  end

end

week9/day-3/iron_topics/app/models/google_search_topic.rb
class GoogleSearchTopic
  include Sidekiq::Worker

  def perform(topic_id)
    topic = Topic.find(topic_id)
    topic.google_results = open("http://www.google.com?q=#{topic.title}").read
    topic.save

    sleep 10
  end
end

week9/day-3/iron_topics/app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic, counter_cache: true

  validates :level, inclusion: [1,2,3,4,5]
end

week9/day-3/iron_topics/app/models/internet_email_sender.rb
class InterestEmailSender
  def initialize(topic)
    @topic = topic
  end

  def send_email
    @topic.interests.each do |interest|
      # Send email about the interest
    end
  end
end

week9/day-3/iron_topics/app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :interests, dependent: :destroy
  belongs_to :user

  accepts_nested_attributes_for :interests
end

week9/day-3/iron_topics/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:twitter]

  has_many :interests
  
  def self.from_omniauth(auth)
    user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

    user.name         = auth.info.name
    user.email        = auth.info.email
    user.nickname     = auth.info.nickname
    user.access_token = auth.credentials.token
    user.password     = Devise.friendly_token[0,20]
    user.save!

    return user
  end
end

week9/day-3/iron_topics/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # protected
  #
  # # User this if you aren't using devise's authenticate_user!
  # def ensure_logged_in
  #   if current_user.nil?
  #     redirect_to new_user_session_path
  #   end
  # end
end

week9/day-3/iron_topics/app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_markdown_instance_for_the_views

  def filter
    topic = Topic.find(params[:topic_id])
    @interests = topic.interests.where(level: params[:level])
  end

  def index
    @topic = Topic.find(params[:topic_id])

    @interests = @topic.interests
  end

  # /topics/:topic_id/interests/:id
  def show
    @topic = Topic.find(params[:topic_id])

    @interest = @topic.interests.find(params[:id])
  end

  def create
    @interest = Interest.new(interest_params)
    @interest.user_id = current_user.id
    if @interest.valid?
      @interest.save

      # Send an (something?) to the user that created the topic
      # @interest.topic.user  is the user that created the associated topic
      render :create
    else
      redirect_to root_path, alert: "Ooops"
    end
  end

  private

  def load_markdown_instance_for_the_views
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, filter_html: true, no_links: true)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def interest_params
    params.require(:interest).permit(:level, :comment, :topic_id)
  end
end

week9/day-3/iron_topics/app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

week9/day-3/iron_topics/app/controllers/topics_controller.rb
require 'open-uri'

class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :disallow_editing_for_topics_with_interests, only: [:edit, :update]
  before_action :authenticate_user!

  # GET /topics
  # GET /topics.json
  def index
    #    @topics = Topic.all.order("interests_count ASC")
    @topics = Topic.all.includes(:interests).
                        sort_by { |topic| topic.interests.sum(:level) }
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, filter_html: true, no_links: true)
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    @topic.interests.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    respond_to do |format|
      if @topic.save
        GoogleSearchTopic.perform_async(@topic.id)

        # Have to put the user_id in the comment ....
        interest = @topic.interests.first
        interest.user_id = current_user.id
        interest.save

        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @topic = Topic.find(params[:id])

    InterestEmailSender.new(@topic).send_email

    @topic.destroy
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :long_description, :focus_area, interests_attributes: [:level, :comment])
    end

    def disallow_editing_for_topics_with_interests
      if @topic.interests.count > 0
        redirect_to topics_path, alert: "Sorry, you can't edit this since there are already interests"
        return
      end
    end
end

week9/day-3/iron_topics/app/helpers/application_helper.rb
module ApplicationHelper
end

week9/day-3/iron_topics/app/helpers/interests_helper.rb
module InterestsHelper
end

week9/day-3/iron_topics/app/helpers/topics_helper.rb
module TopicsHelper
end

week9/day-3/iron_topics/app/views/interests/_interest.html.erb
<li><%= interest.level %> by <%= interest.user.name %> who said <%= @markdown.render(interest.comment).html_safe %></li>

week9/day-3/iron_topics/app/views/interests/create.js.erb
$("<%= escape_javascript(render @interest) %>").hide().css({"color": "green"}).prependTo("#interests").fadeIn();

week9/day-3/iron_topics/app/views/interests/filter.js.erb
$("#interests").html( $("<%= escape_javascript(render @interests) %>") )

week9/day-3/iron_topics/app/views/interests/index.html.erb
<% @interests.each do |interest| %>
  <ul>
  <li><%= interest.level %></li>
  <li><%= interest.comment %></li>
  </ul>
<% end %>

week9/day-3/iron_topics/app/views/interests/show.html.erb
The topic is:
<ul>
<li><%= @topic.title %></li>
</ul>

The interest is

<ul>
<li><%= @interest.level %></li>
<li><%= @interest.comment %></li>
</ul>

week9/day-3/iron_topics/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IronTopics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Really logout?' } %>

<%= yield %>

</body>
</html>

week9/day-3/iron_topics/app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br>
    <%= f.text_area :long_description %>
  </div>
  <div class="field">
    <%= f.label :focus_area %><br>
    <%= f.text_field :focus_area %>
  </div>

  <%= f.fields_for :interests do |interest_fields| %>
    <div class="field">
    <%= interest_fields.label :level %>
    <%= interest_fields.text_field :level %>
    </div>
    <div class="field">
    <%= interest_fields.label :comment %>
    <%= interest_fields.text_area :comment %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

week9/day-3/iron_topics/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

week9/day-3/iron_topics/app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Long description</th>
      <th>Focus area</th>
      <th># of interests</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.long_description %></td>
        <td><%= topic.focus_area %></td>
        <td><%= topic.interests_count %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

week9/day-3/iron_topics/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

week9/day-3/iron_topics/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<% if @topic.google_results %>
  <%= @topic.google_results.html_safe %>
<% else %>
   No google results yet!
<% end %>

<p>
  <strong>Long description:</strong>
  <div class="markdown">
  <%= @markdown.render(@topic.long_description).html_safe %>
  </div>
</p>

<p>
  <strong>Focus area:</strong>
  <%= @topic.focus_area %>
</p>

<%= select_tag(:interest_level, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5]]), data: {"topic_id" => @topic.id }); %>

<%= form_for([@topic, Interest.new], remote: true) do |f| %>
  <%= f.hidden_field :topic_id, value: @topic.id %>
  <div class="field">
  <%= f.label :level %>
  <%= f.text_field :level %>
  </div>
  <div class="field">
  <%= f.label :comment %>
  <%= f.text_area  :comment %>
  </div>
  <%= f.submit %>
<% end %>

<ul id="interests">
  <%= render @topic.interests %>
</ul>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>